const loader=document.getElementById('loader');const app=document.getElementById('app');const modal=document.getElementById('auth-modal');const content=document.getElementById('auth-content');
window.addEventListener('load',()=>{setTimeout(()=>{loader.classList.add('done');app.classList.remove('is-hidden')},1200)});
const signupMarkup=()=>`<div class="auth-content"><h2>Create your workspace.</h2><p>Start with the business tools you actually need.</p><form class="auth-form" id="signup-form"><div class="field"><label>Full name</label><input required autocomplete="name" placeholder="Your name"></div><div class="field"><label>Business email</label><input required type="email" autocomplete="email" placeholder="you@business.com"></div><div class="field"><label>Password</label><input required type="password" minlength="8" autocomplete="new-password" placeholder="At least 8 characters"></div><button class="btn btn-primary btn-large" type="submit">Create account →</button></form><div class="or">OR</div><button class="btn google" type="button">Continue with Google</button><div class="auth-switch">Already have an account? <button type="button" data-auth-switch="login">Log in</button></div></div>`;
const loginMarkup=()=>`<div class="auth-content"><h2>Welcome back.</h2><p>Sign in to your Vero workspace.</p><form class="auth-form" id="login-form"><div class="field"><label>Email</label><input required type="email" autocomplete="email" placeholder="you@business.com"></div><div class="field"><label>Password</label><input required type="password" autocomplete="current-password" placeholder="Your password"></div><button class="btn btn-primary btn-large" type="submit">Log in →</button></form><div class="or">OR</div><button class="btn google" type="button">Continue with Google</button><div class="auth-switch">New to Vero? <button type="button" data-auth-switch="signup">Create an account</button></div></div>`;
const choicesMarkup=()=>`<div class="auth-content"><div class="choice-title">What do you need?</div><div class="choice-sub">Select the areas you want Vero to help you with. You can change these later.</div><div class="choices"><button class="choice"><strong>Get Online</strong><span>Profile, catalogue, business link and QR</span></button><button class="choice"><strong>Get Customers</strong><span>Leads, enquiries and follow-ups</span></button><button class="choice"><strong>Get Paid</strong><span>Invoices, payment requests and receipts</span></button><button class="choice"><strong>Run My Business</strong><span>Customers, products and transactions</span></button><button class="choice"><strong>Understand My Business</strong><span>Reports and real business insights</span></button></div><button class="btn btn-primary continue" id="continue-choice">Continue →</button></div>`;
function openAuth(mode='login'){modal.classList.add('open');modal.setAttribute('aria-hidden','false');content.innerHTML=mode==='signup'?signupMarkup():loginMarkup();wireAuth()}
function closeAuth(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function wireAuth(){document.querySelectorAll('[data-auth-switch]').forEach(b=>b.onclick=()=>{content.innerHTML=b.dataset.authSwitch==='signup'?signupMarkup():loginMarkup();wireAuth()});document.getElementById('signup-form')?.addEventListener('submit',e=>{e.preventDefault();content.innerHTML=choicesMarkup();wireChoices()});document.getElementById('login-form')?.addEventListener('submit',e=>{e.preventDefault();content.innerHTML='<div class="auth-content"><h2>Authentication is ready for integration.</h2><p>The interface is wired. Connect your production auth provider to enable real account sessions.</p><button class="btn btn-primary btn-large" onclick="closeAuth()">Back to Vero</button></div>'})}
function wireChoices(){document.querySelectorAll('.choice').forEach(c=>c.onclick=()=>c.classList.toggle('selected'));document.getElementById('continue-choice').onclick=()=>{content.innerHTML='<div class="auth-content"><h2>Workspace setup.</h2><p>Your selected services will shape the Vero workspace. Production business creation and database persistence should be connected to the backend before launch.</p><button class="btn btn-primary btn-large" onclick="closeAuth()">Enter Vero →</button></div>'}}
document.querySelectorAll('[data-open-auth]').forEach(b=>b.onclick=()=>openAuth(b.dataset.openAuth));document.querySelectorAll('[data-close-auth]').forEach(b=>b.onclick=closeAuth);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAuth()});
